- broker/cluster/events.go
- broker/cluster/events_test.go
- broker/cluster/peer.go
- broker/cluster/swarm.go
- broker/cluster/swarm_test.go
- broker/conn.go
- broker/handlers.go
- broker/handlers_dto.go
- broker/handlers_test.go
- broker/message/message.go
- broker/message/message_test.go
- broker/message/sub.go
- broker/message/sub_test.go
- broker/message/subtrie.go
- broker/message/subtrie_test.go
- broker/query.go
- broker/service.go
- broker/storage/memory.go
- broker/storage/memory_test.go
- broker/storage/storage.go
- broker/storage/storage_test.go
- utils/codec.go
- utils/codec_test.go
This creates a streamlined and unified `message` package containing a `Message` struct and a `Frame` struct. This package is now used by storage and message forwarding implementations . I also did some refactoring work to make the code cleaner and easier to read.
> Created a unified message package and refactored

- broker/cluster/swarm.go
- broker/conn.go
- broker/query.go
- broker/service.go
- broker/status.go
This one is kinda tricky, the `QueryManager` implements a Subscriber interface and subscribes to `0/query/` so it can receive queries sent from other nodes of the cluster. However, it did not ignore its own requests so it would attempt to find and connect to its own "peer" and issue gossip query through, which would then fail.
> fixed cluster query which would answer its own requests

- broker/conn.go
This adds a default deadline to the underlying transport when processing.
> added a read/write deadline

- broker/cluster/swarm.go
- broker/cluster/swarm_test.go
With this, the broker will resolve a seed domain name and attempt to join all the nodes registered (see  https://github.com/emitter-io/emitter/issues/18). This should make simultaneous cluster restarts more robust.
> resolving the seed hostname on join

- broker/cluster/swarm.go
- broker/cluster/swarm_test.go
- broker/service.go
- broker/storage/http.go
- broker/storage/http_test.go
- broker/storage/memory.go
- broker/storage/memory_test.go
- broker/storage/storage_test.go
- network/address/address.go
- network/address/address_test.go
- network/http/http.go
- network/http/http_test.go
- network/http/mock.go
- network/http/mock_test.go
- security/contract.go
- security/contract_test.go
- security/usage/metering.go
- security/usage/metering_test.go
Adding an experimental implementation of HTTP-based message storage. This currently supports only `binary` encoding of message frames, but may be extended to `JSON` in future.
> adding HTTP message storage provider

- .vscode/settings.json
- broker/handlers.go
- broker/handlers_dto.go
- broker/handlers_test.go
- security/crypto.go
- security/crypto_test.go
- security/key.go
- security/key_test.go
Hi guys.
I really don't want to be a pain...
but I would like to get the contribution for this feature in the project if it doesn't bother you too much.
So this PR is basically a cherry-pick of your [other PR](https://github.com/emitter-io/emitter/pull/81).
The main difference is that I also use the byte 14 (that was unused in your PR) so we can have 23 levels depth channels.
> Feature: channel-specific keys and matching, retro-compatible

- vendor/github.com/emitter-io/config/config.go
- vendor/github.com/emitter-io/config/config_plugin.go
- vendor/github.com/emitter-io/config/config_plugin_darwin.go
- vendor/vendor.json
Get rid of the following warning on OSX.
```
ld: warning: PIE disabled. Absolute addressing (perhaps -mdynamic-no-pic) not allowed in code signed PIE, but used in type..eqfunc.[106]string from /var/folders/hz/nqhk5_3n4v9_rkgjdmqk5k5w0000gn/T/go-link-728052133/go.o. To fix this warning, don't compile with -mdynamic-no-pic or link with -Wl,-no_pie
```
> Update github.com/emitter-io/config vendor to latest version

- broker/message/message.go
- broker/message/sub.go
- broker/message/sub_test.go
- broker/message/subtrie.go
- broker/message/subtrie_test.go
There's an issue with the current concurrent trie. This PR proposes a simpler locked one with some optimisations. This needs a bit more testing and possibly a first-level sync.Map for increased throughput on the multi-tenant setup.
Following issues seem to be related: https://github.com/emitter-io/emitter/issues/104, https://github.com/emitter-io/emitter/issues/23 and will hopefully be fixed with this.
> Feature: simplifying subsription matching by using a locked trie

- broker/service.go
- config/config.go
- config/config_test.go
- vendor/github.com/emitter-io/config/config.go
- vendor/github.com/emitter-io/config/http.go
- vendor/github.com/emitter-io/config/vault.go
- vendor/github.com/gorilla/websocket/client.go
- vendor/github.com/gorilla/websocket/proxy.go
- vendor/github.com/gorilla/websocket/server.go
- vendor/github.com/stretchr/objx/Gopkg.lock
- vendor/github.com/stretchr/objx/accessors.go
- vendor/github.com/weaveworks/mesh/README.md
- vendor/vendor.json
Autocert TLS-SNI is being faded out and not supported anymore, this PR introduces simple http validation. https://community.letsencrypt.org/t/2018-01-11-update-regarding-acme-tls-sni-and-shared-hosting-infrastructure/50188
> Support for letsencrypt http-1 validation

- broker/cluster/peer.go
- broker/message/message.go
- broker/message/message_test.go
removing a potential lock contention by swapping to a new object - might do double-buffering instead going forward
> Removed peer encode out of the lock

- broker/handlers.go
- message/id.go
- security/channel.go
- security/channel_test.go
This PR adds `from` - `until` query options allowing to query message storage using time bounds. Currently this will only work for our `ssd` storage backend.
> added from/until query options

- Dockerfile
This uses latest Golang Alpine Docker image and base image for runtime as Alpine.
Fixes issue #145
> Dockerfile to use Multi-Stage builds (#145)

- internal/provider/monitor/statsd.go
This PR makes datadog statsd format as default one
> Default to datadog statsd tag format

- internal/broker/cluster/events.go
- internal/broker/cluster/events_test.go
- internal/broker/cluster/memberlist.go
- internal/broker/cluster/memberlist_test.go
- internal/broker/cluster/peer.go
- internal/broker/cluster/swarm.go
- internal/broker/cluster/swarm_test.go
- internal/broker/query.go
This PR fixes few issues with the subscription state. 
- When a server is removed and added again to the cluster, it no longer resubscribes to itself. 
- When a peer is detected as offline, its subscriptions are no longer lingering in the LLWSet.
- When a broker joins the cluster indirectly, it no longer misses some of the subscriptions.
> Multiple subscription fixes

- internal/broker/conn.go
- internal/broker/handlers.go
- internal/broker/handlers_dto.go
- internal/broker/service_test.go
- internal/security/channel.go
- internal/security/channel_test.go
This PR introduces a way of skipping self-published messages. This is useful if a client is using same topic to send and receive messages, and has both publish and subscribe capabilities.
> Feature: Added a 'me=0' option to skip self-published events

- internal/broker/conn.go
- internal/broker/handlers.go
- internal/broker/handlers_dto.go
- internal/broker/handlers_test.go
- internal/security/channel.go
- internal/security/channel_test.go
This PR adds request IDs for each 'emitter/.../' response. These requests IDs only work with QoS=1 as they're actually MQTT message IDs.
> Added request ID for emitter responses

- README.md
- internal/broker/conn.go
- internal/broker/service_test.go
- internal/config/config.go
- internal/config/config_test.go
- internal/network/mqtt/mqtt.go
- internal/network/mqtt/mqtt_test.go
As of now maximum message size is fixed to default 64KB. If a message arrives which is bigger than this the connection is dropped. 
So adding max message size as configurable would let users fine tune the max size.
> Make Maximum Message Size as configurable.

- appveyor.yml
- go.mod
- go.sum
- internal/broker/handlers.go
- internal/broker/handlers_test.go
- internal/broker/service.go
- internal/message/id.go
- internal/message/id_test.go
- internal/message/sub.go
- internal/message/sub_test.go
- internal/message/subtrie.go
- internal/message/subtrie_test.go
- internal/security/channel.go
- internal/security/channel_test.go
- internal/security/hash/murmur_test.go
A shared subscription is a mechanism for distributing messages to a set of subscribers to shared subscription topic, such that each message is received by only one subscriber. This contrasts with normal subscriptions where each subscriber will receive a copy of the published message.
A shared subscription is on the form `$share/sharename/channel` and subscribers to this topic will receive messages published to the channel. The messages will be distributed according to the defined distribution policy.
> Added support for shared subscriptions

- internal/broker/handlers.go
- internal/broker/handlers_dto.go
So that a status can be requested without passing the "changes" parameter and therefore without touching the Trie.
> Allow nil for Changes in Presence

- internal/provider/contract/contract.go
- internal/provider/usage/usage.go
Hi, we updated some exported function comments based on best practices from [Effective Go](https://golang.org/doc/effective_go.html#commentary). It’s admittedly a relatively minor fix up. Does this help you?
> Fix function comments based on best practices from Effective Go

- internal/broker/handlers.go
So that when subscribing to presence messages without request a status, there isn't a status message with empty Who array sent anymore.
> Fix empty status msg when sub to presence

- Dockerfile
With go 1.11 building code can be (needs to be) done outside of the gopath.
Git access is also needed to download the dependencies.
> support building using go modules

- internal/broker/cluster/peer.go
- internal/broker/cluster/peer_test.go
- internal/message/message.go
- internal/message/message_test.go
Improved the performance encoding/decoding of frames by adding a buffer pool. This is safe, given the memory copy is performed during Snappy encoding anyway.
> optimised message frame encoding/decoding

- internal/message/codec.go
- internal/message/codec_test.go
- internal/message/message.go
- internal/message/message_test.go
- internal/provider/storage/memory.go
- internal/provider/storage/memory_test.go
- internal/provider/storage/ssd.go
- internal/provider/storage/ssd_test.go
- internal/provider/storage/storage_test.go
A few changes with this PR:
1. We're using a zero copy codec in order to decrease memory allocations during encoding and decoding of message structs. This speeds up the decoding by 6x less allocations and effectively makes it 1 allocation per message per decode. Overall decoding time is reduced by around 2x.
2. Fixed a bug with in-memory message storage where messages would not be properly sorted, resulting in incorrect behavior.
3. All messages stored in both in-memory and ssd storages are now snappy compressed. This should result in less storage costs and faster storage altogether.
4. In-memory message storage now supports range queries and should have the same behavior as the SSD storage now.
> no-copy message encoding & fixed memory sort

- appveyor.yml
- internal/broker/service.go
- internal/config/config.go
- internal/network/listener/conn.go
- internal/network/listener/conn_test.go
- internal/network/listener/listener.go
- internal/network/listener/listener_test.go
This makes the write rate configurable by adding `writeRate` to the `limit` configuration. Write rate allows to rate-limit the underlying socket flushes and greatly (15-20x from our benchmarks) increases the througput of emitter broker. The value is set to a reasonnable 60 write/s per connection. Keep in mind this is not limiting the QpS but merely limiting the amount of syscalls going out to the OS.
> feat: made write rate configurable

- .vscode/settings.json
- internal/broker/conn.go
- internal/broker/conn_test.go
- internal/broker/handlers_test.go
- internal/broker/service.go
- internal/config/config.go
- internal/network/listener/listener.go
This can be used in order to protect the broker from misbehaving clients.  This PR also changes the previous `writeRate` to `flushRate` which is a more appropriate name.
```
// The maximum messages per second allowed to be processed per client connection. This
// effectively restricts the QpS for an individual connection.
ReadRate int `json:"readRate,omitempty"`
// The maximum socket write rate per connection. This does not limit QpS but instead
// can be used to scale throughput. Defaults to 60.
FlushRate int `json:"flushRate,omitempty"`
```
> Added a read rate limiter which allows limiting the read QpS per client

- internal/broker/cluster/peer.go
- internal/message/message.go
- internal/message/message_test.go
This adds chunking before sending through to the gossi unicast, given that the max frame is 10MB we can send at once.
> Added chunking for gossip unicast

- internal/broker/bench_test.go
- internal/broker/handlers.go
- internal/broker/service.go
- internal/config/config.go
- main.go
This PR adds a debug mode flag in the config. Ppprof HTTP endpoints are now by default disabled and you'll need to flip the flag on to enable them.
> Added debug mode configuration

- build.bat
- internal/command/load/load_test.go
- internal/command/version/version.go
- internal/command/version/version_test.go
- main.go
This PR introduces a `version` command which simply prints the version of the executable along with the git commit SHA. Use `emitter version` to run it.
> Added a version command into the executable

- internal/broker/service.go
On ARM (Raspberry Pi 3) following error occurs when starting emitter:
```
2019/12/09 11:54:58 [async] panic recovered: runtime error: invalid memory address or nil pointer dereferences
goroutine 1 [running]:
runtime/debug.Stack(0x28fbaa4, 0xabcee0, 0x116b7a8)
/usr/local/go/src/runtime/debug/stack.go:24 +0x78
github.com/emitter-io/emitter/internal/async.handlePanic()
/go/src/github.com/emitter-io/emitter/internal/async/timer.go:58 +0x3c
panic(0xabcee0, 0x116b7a8)
/usr/local/go/src/runtime/panic.go:679 +0x194
runtime/internal/atomic.goLoad64(0x2a3075c, 0xb6863e, 0xa)
/usr/local/go/src/runtime/internal/atomic/atomic_arm.go:131 +0x1c
github.com/emitter-io/emitter/internal/broker.(*sampler).Snapshot(0x280ee00, 0x8, 0x2810b40, 0x0)
/go/src/github.com/emitter-io/emitter/internal/broker/status.go: …
```
> Fixed alignment of int64, to be able to access it with atomic.LoadInt64

- internal/network/mqtt/mqtt.go
see https://github.com/emitter-io/emitter/issues/305
> fix(305)Panic when receive bad packet

- internal/broker/service.go
- internal/config/config.go
- internal/message/id.go
- internal/message/sub.go
- internal/message/subtrie.go
- internal/message/subtrie_test.go
- internal/security/channel.go
- internal/service/pubsub/subscribe.go
I made a patch so the topic matching would follow MQTT specification.
emitter.conf
``` json
{
"matcher": "mqtt"
}
```
or just run
```sh
EMITTER_MATCHER=mqtt ./emitter
```
> MQTT topic matching strategy

- internal/broker/service.go
This fixes the spot in `internal/broker` where `NewService()` required a `context.Context` as its argument and then immediately clobbered it with `context.Background()`.
> internal/broker: fix clobbered context

- internal/network/http/http_test.go
This fixes two dropped `err` variables in the tests for the `internal/network/http` package.
> internal/network/http: fix dropped test errors

- internal/network/mqtt/buffer.go
- internal/network/mqtt/mqtt.go
- internal/provider/storage/ssd.go
- internal/provider/storage/ssd_test.go
- internal/provider/storage/storage_test.go
- internal/service/pubsub/subscribe.go
From the begining, mqtt.go defines a maximum size for a response. However if the limit was met, it resulted in an error and no message was sent. Now, the Query itself limits the size of a frame and messages are sent to the client, but only those whose total size <= to the total size of allowed in a response.
Implications on the current API: for a subscribe request with a Last=X parameter, the client will receive the last messages whose total size is <= to the max size of a response, with a maximum of X messages. This behavior is an improvement over just getting an error.
> Limit the size of a response

- internal/broker/service.go
- internal/provider/storage/memory_test.go
- internal/provider/storage/ssd.go
- internal/provider/storage/ssd_test.go
- internal/provider/storage/storage.go
- internal/provider/storage/storage_test.go
- internal/service/history/history.go
- internal/service/history/history_test.go
- internal/service/history/service.go
- internal/service/pubsub/lastwill_test.go
- internal/service/pubsub/publish_test.go
- internal/service/pubsub/subscribe.go
- internal/service/pubsub/subscribe_test.go
The history api allows to retrieve any number of messages stored in a channel. As the number of messages that can return in a single response is limited by the size of a response (as per #413), a system of pagination is required. This system is implemented with the introduction of the StartFromID query parameter. An client that already received a response with a certain number of messages can send a new request to the API with the StartFromID set to the ID of the last message it received. The storage query will then start retreiving messages starting at that ID to provide the API the next page of messages in its response.
> Adds the new history API

- internal/broker/service.go
- internal/provider/storage/memory_test.go
- internal/provider/storage/ssd_test.go
- internal/provider/storage/storage.go
- internal/provider/storage/storage_test.go
- internal/service/pubsub/subscribe_test.go
> [FIX] Storage implement the Surveyee interface

- internal/service/keyban/keyban.go
Keyban just didn't work. There was a strange channel check while all that was required was to check the validity of the master key. See straighforward code change, for more info.
> [DRAFT][FIX] Keyban now correctly checks the master key validity

- internal/service/me/me.go
- internal/service/me/requests.go
- internal/service/presence/presence.go
- internal/service/presence/requests.go
@kelindar Note that we seem to only ever return a status when everything went fine and it's a 200. Was this the intention?
NOTE that we also send a Response with 200 in the case of a response to
a Presence request with the status flag set to false. In this case, we
don't gather the presence statuses on the brokers, but we need to send
an empty response instead of just nil. This will allow for an RPC call
on Presence. See the SDKs (Go in particular).
> [IMP] Adds a Status (200) field to Me and Presence response for consistency

- internal/service/history/history.go
...not a string. Also renaming Topic to Channel.
[BREAKING CHANGE]
> [FIX] History: Payload had to be []bytes
